# Spring Boot application name and port
spring.application.name=githubreport
server.port=8083

# GitHub Personal Access Token (PAT) with 'repo' and 'read:org' scopes
github.token=${GITHUB_TOKEN}
# GitHub API base URL (always https://api.github.com)
github.api.base-url=https://api.github.com

# GitHub organization name (exactly as in GitHub)
github.org-name=yaminiveerabommaorg